### ISSUE TITLE
User Story: Administrator Create New Polls

### ISSUE THREAD

**Issue by dushanka-dev** [dushanka-dev/My-First-Agile-Project#5]
As a **administrator** I can **publish a poll** so that **can easily create new polls**

## **Acceptance Criteria:**

- Acceptance Criteria 1: New blank form template should be available to publish with one click.
- Acceptance Criteria 2: Blank form should be prepopulated with current date and website logo.
- Acceptance Criteria 3: New notification email should be sent to users once published.

## **Tasks**

- [x] Task 1: Create HTML and CSS to new form.
- [ ] Task 2: Add website logo and styling.
- [ ] Task 3: Use JavaScript to add current date to form.
- [ ] Task 4: Connect emailjs to form so can send emails to users.
