### ISSUE TITLE
User Story: Voters feedback section

### ISSUE THREAD

**Issue by dushanka-dev** [dushanka-dev/My-First-Agile-Project#6]
As a **Voter** I can **send feedback** so that **Administrator understand my thought on new polls**

## **Acceptance Criteria:**

- Acceptance Criteria 1: Feedback section should be after the voting section
- Acceptance Criteria 2: Section should have smiley and sad face emoji for user to select
- Acceptance Criteria 3: Once feedback is sent give user confirmation text that feedback sent successfully.

## **Tasks**

- [ ] Task 1: Create feedback text area using bootstrap forms
- [ ] Task 2: Show voter feedback sent confirmation message
- [ ] Task 3: Add smileys to form
