### ISSUE TITLE
User Story: Vote anonymously

### ISSUE THREAD

**Issue by dushanka-dev** [dushanka-dev/My-First-Agile-Project#7]
As a **Voter** I can **vote anonymously** so that **my name is and personal information hidden**

## **Acceptance Criteria:**

- Acceptance Criteria 1: Give user option to vote without add name
- Acceptance Criteria 2: Add checkbox for user to select
- Acceptance Criteria 3: Once vote is submitted give user message confirming feedback sent anonymously

## **Tasks**

- [ ] Task 1: Add checkbox to voting poll form
- [x] Task 2: When checkbox is selected remove personal details form sections
- [ ] Task 3: Add confirmation text area
